id: 17af6be35b4844bcb47db90c5cb2ae7d
initial_creation_type: ocr
source_metadata:
  volumes:
    716ac9bf7a4446a38a549610e8490404:
      base_file: v005.txt
      image_group_id: I1PD95850
      title: ''
      total_pages: 2069
      volume_number: 5
